import { Inter } from "next/font/google";
import "./globals.css";
import DesktopNav from "./compontents/nav-desktop";
import MobileNav from "./compontents/nav-mobile";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Bluebox Storage Cork",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <DesktopNav />
        </div>
        <div>
          <MobileNav />
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
